# This module defines constant values for environment variable names used in the application.

GITHUB_TOKEN_ENV_NAME = 'GITHUB_TOKEN'
GITHUB_REPOSITORY_NAME_ENV_NAME = 'GITHUB_REPOSITORY_NAME'
GITHUB_REPOSITORY_OWNER_ENV_NAME = 'GITHUB_REPOSITORY_OWNER'

YOUTRACK_URL_ENV_NAME = 'YOUTRACK_URL'
YOUTRACK_TOKEN_ENV_NAME = 'YOUTRACK_TOKEN'
YOUTRACK_PROJECT_SHORT_NAME_ENV_NAME = 'YOUTRACK_PROJECT_SHORT_NAME'

SYNC_INTERVAL_MINUTES_ENV_NAME = 'SYNC_INTERVAL_MINUTES'